apiVersion: v1
kind: Service
metadata:
  name: mssql-service
  namespace: mssql
  labels:
    app: mssql-server
spec:
  selector:
    app: mssql-server
  type: LoadBalancer
  ports:
    - port: 1433
      targetPort: 1433