{{- if .Values.apps.nginxIngressController.enabled }}

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-ingress-cotroller
  namespace: argocd
spec:
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  destination:
    namespace: nginx-ingress
    server: {{ .Values.spec.destination.server }}
  project: core
  source:
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: {{ .Values.apps.nginxIngressController.version }}
    helm:
      releaseName: nginx-ingress-cotroller
      values: {{- include "core.apps.nginxIngressController.values" . | toYaml | nindent 8 }}
      
{{- end }}core-components