{{- if .Values.apps.longhorn.enabled }}

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn-system
  namespace: argocd
spec:
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  destination:
    namespace: longhorn-system
    server: {{ .Values.spec.destination.server }}
  project: core
  source:
    chart: longhorn
    repoURL: https://charts.longhorn.io
    targetRevision: {{ .Values.apps.longhorn.version }}
    helm:
      releaseName: longhorn
      values: {{- include "core.apps.longhorn.values" . | toYaml | nindent 8 }}

{{- end }}