apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mssql-statefulset
  namespace: argocd
spec:
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
  destination:
    namespace: mssql
    server: {{ .Values.spec.destination.server }}
  project: shared
  source:
    path: apps/mssql-statefulset/
    repoURL: https://github.com/Widazz/k8s-deploy/
    targetRevision:  {{ .Values.spec.targetRevision }}
