{{ if .Values.apps.nginxIngressController.enabled }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-ingress-controller
  namespace: argocd
spec:
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
  destination:
    namespace: nginx-ingress
    server: {{ .Values.spec.destination.server }}
  project: core
  source:
    chart: nginx-ingress-controller
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: {{ .Values.apps.nginxIngressController.version }}
    helm:
      releaseName: nginx-ingress-controller
      values: {{ include "core.apps.nginxIngressController.values" . | toYaml | nindent 8 }}
---
{{ end }}