apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak
  namespace: argocd
spec:
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
  destination:
    namespace: keycloak
    server: {{ .Values.spec.destination.server }}
  project: core
  source:
    chart: keycloak
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: {{ .Values.apps.keycloak.version }}
    helm:
      releaseName: keycloak
      values: {{- include "core.apps.keycloak.values" . | toYaml | nindent 8 }}
