{{- define "group2.billing.values" -}}

replicaCount: 1

image:
  repository: louthier/billing-service
  pullPolicy: Always
  tag: "latest"

env:
  "ASPNETCORE_ENVIRONMENT": "Production"
  "DB_CONNECTION_STRING": ""
  "KEYCLOAK_ISSUER": ""
  "KEYCLOAK_RSA_PUBLIC_KEY": ""
  "RABBITMQ_HOST": ""
  "RABBITMQ_VIRTUAL_HOST": ""
  "RABBITMQ_PASSWORD": ""
  "RABBITMQ_USERNAME": ""
  "STRIPE_PRODUCT_DEMOTE_ID": ""
  "STRIPE_PRODUCT_PROMOTE_ID": ""
  "STRIPE_PUBLISHABLE_KEY": ""
  "STRIPE_SECRET_KEY": ""
  "STRIPE_WEBHOOK_SECRET": ""

imagePullSecrets:
  - name: regcred

service:
  type: ClusterIP
  port: 80

autoscaling:
  enabled: false

serviceAccount:
  create: false

{{- end -}}
