apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: metallb-pool
  namespace: metallb-system
spec:
  addresses:
  - {{ .Values.metallb.addressPool }}
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: metallb-advertiser
  namespace: metallb-system
spec:
  ipAddressPools:
    - metallb-pool
  nodeSelectors:
  - matchLabels:
      node-role.kubernetes.io/worker: worker