{{ define "core.apps.longhorn.values" }}
---
ingress: 
  enabled: 
    ? 
      .Values.apps.longhorn.ingress.enabled: ~
    : false
  host: 
    ? 
      .Values.apps.longhorn.ingress.hostname: ~
    : ~
  ingressClassName: nginx
  path: /
  secureBackends: false
  tls: true
  tlsSecret: longhorn.local-tls
---
{{ end }}
