apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
  destination:
    namespace: argocd
    server: {{ .Values.spec.destination.server }}
  project: core
  source:
    path: apps/argo-cd/
    repoURL: https://github.com/Widazz/k8s-deploy/
    targetRevision:  {{ .Values.spec.targetRevision }}